Add `update-database-schema` to providence deployment.
+ Support for `preDeploy` hook to check for correct setting of
  `COLLECTIVEACCESS_HOME` environment variable.
+ Add call to `caUtils update-database-schema` in `postDeploy`
  hook after installing providence component.

diff --git a/config/rwahs/components/providence b/config/rwahs/components/providence
--- a/config/rwahs/components/providence
+++ b/config/rwahs/components/providence
@@ -10,7 +10,18 @@ repo='rwahs/providence'
 repoDefaultTargetCommitish='master-fix'
 targetParent='web/providence'
 
+function preDeploy {
+    if [ ! -v COLLECTIVEACCESS_HOME ]; then
+        echo "Error: The COLLECTIVEACCESS_HOME environment variable is required to deploy the 'providence' component" >&2
+        exit 1
+    elif [ ! -f "${COLLECTIVEACCESS_HOME}/support/bin/caUtils" ]; then
+        echo "Error: The COLLECTIVEACCESS_HOME environment variable does not point to a valid providence installation" >&2
+        exit 1
+    fi
+}
+
 function postDeploy {
+    "${COLLECTIVEACCESS_HOME}/support/bin/caUtils" update-database-schema
     sudo service apache2 restart
     sudo service php5-fpm restart
 }
